name: Build SBOM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-sbom:
    runs-on: ubuntu-latest
    env:
      SBOM_OUTPUT_DIR: sbom-output
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install CycloneDX
        run: npm install -g @cyclonedx/cyclonedx-node-module

      - name: Generate SBOM
        run: cyclonedx --input-dir . --output ${{ env.SBOM_OUTPUT_DIR }}/bom.json --output-format json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: cyclonedx-sbom
          path: ./${{ env.SBOM_OUTPUT_DIR }}/bom.json
